version: '3'

services: 
  src: 
    image: msshoppingserver-dev
    build: .
    ports: 
      - "3333:3333"
    volumes: 
      - ./dist:/src/dist
      - ./node_modules:/src/node_modules
  database: 
    image: postgres
    environment: 
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=2553218858"
      - "POSTGRES_DB=msshopping"
    ports: 
      - 5441:5432
    volumes: 
      - pg-data:/var/lib/postgresql/data
volumes: 
  pg-data:
